### ISSUE TITLE
workaround locally

### ISSUE THREAD

**Issue by zirconias** [IdanFridman/BootNetflixExample#2]
is there any way to launch it locally ? 
you can tag this as documentation issue!
thanks

**Comment by IdanFridman** [comment]
@zirconias, You should be able to clone build and run it locally. Do you have any issues ?

**Comment by zirconias** [comment]
yes this is the output of ./gradlew build

xirconias@xirc-mac:~/work/learn/spring/BootNetflixExample$ ./gradlew build
:core/baggage-service:compileJava UP-TO-DATE
:core/baggage-service:processResources UP-TO-DATE
:core/baggage-service:classes UP-TO-DATE
:core/baggage-service:jar
:core/baggage-service:bootRepackage
:core/baggage-service:assemble
:core/baggage-service:compileTestJava UP-TO-DATE
:core/baggage-service:processTestResources UP-TO-DATE
:core/baggage-service:testClasses UP-TO-DATE
:core/baggage-service:test UP-TO-DATE
:core/baggage-service:check UP-TO-DATE
:core/baggage-service:build
:core/coupon-service:compileJava UP-TO-DATE
:core/coupon-service:processResources UP-TO-DATE
:core/coupon-service:classes UP-TO-DATE
:core/coupon-service:jar
:core/coupon-service:bootRepackage
:core/coupon-service:assemble
:core/coupon-service:compileTestJava UP-TO-DATE
:core/coupon-service:processTestResources UP-TO-DATE
:core/coupon-service:testClasses UP-TO-DATE
:core/coupon-service:test UP-TO-DATE
:core/coupon-service:check UP-TO-DATE
:core/coupon-service:build
:core/flight-booking-service:compileJava UP-TO-DATE
:core/flight-booking-service:processResources UP-TO-DATE
:core/flight-booking-service:classes UP-TO-DATE
:core/flight-booking-service:jar
:core/flight-booking-service:bootRepackage
:core/flight-booking-service:assemble
:core/flight-booking-service:compileTestJava UP-TO-DATE
:core/flight-booking-service:processTestResources UP-TO-DATE
:core/flight-booking-service:testClasses UP-TO-DATE
:core/flight-booking-service:test UP-TO-DATE
:core/flight-booking-service:check UP-TO-DATE
:core/flight-booking-service:build
:core/flight-integration-service:compileJava UP-TO-DATE
:core/flight-integration-service:processResources UP-TO-DATE
:core/flight-integration-service:classes UP-TO-DATE
:core/flight-integration-service:jar
:core/flight-integration-service:bootRepackage
:core/flight-integration-service:assemble
:core/flight-integration-service:compileTestJava UP-TO-DATE
:core/flight-integration-service:processTestResources UP-TO-DATE
:core/flight-integration-service:testClasses UP-TO-DATE
:core/flight-integration-service:test
2015-12-26 20:47:42.867  INFO 9873 --- [       Thread-4] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@167b7753: startup date [Sat Dec 26 20:47:33 CET 2015]; root of context hierarchy

com.bootnetflix.flight_integration_service.FlightIntegrationTest > flightTest FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.springframework.beans.factory.BeanCreationException
                Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException

1 test completed, 1 failed
:core/flight-integration-service:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':core/flight-integration-service:test'.
  
  > There were failing tests. See the report at: file:///Users/xirconias/work/learn/spring/BootNetflixExample/core/flight-integration-service/build/reports/tests/index.html
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 27.411 secs

**Comment by zirconias** [comment]
this is the report of test which causes the build failure 

https://gist.github.com/zirconias/adb5764aa33f75c0bc6b
